# Build stage
FROM golang:1.24-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
WORKDIR /app/cmd/agent
RUN go build -o /agent .

# Final stage
FROM alpine:latest
WORKDIR /app
COPY --from=builder /agent ./agent
COPY .env ./
EXPOSE 8080
ENTRYPOINT ["./agent"]